### ISSUE TITLE
MS Edge 브라우져에서 card-content의 본문 침범

### ISSUE THREAD

**Issue by whatugonnado** [evan-moon/evan-blog#5]
예시 도메인 : https://evan-moon.github.io/2019/10/08/what-is-http3/?fbclid=IwAR1BO3MWGoZ0gu8B8iqHEPMA5e7A2Z4_O9MYWYRSmbbo35tIEqcZP76FxVg

확인 부탁드립니다

**Comment by evan-moon** [comment]
https://github.com/evan-moon/evan-blog/pull/6 에서 수정되었슴다

**Comment by evan-moon** [comment]
https://github.com/evan-moon/evan-blog/pull/6 에서 수정되었슴다

**Comment by whatugonnado** [comment]
[첨부파일](https://i.imgur.com/TS2qw7K.png) 아직인듯 합니다 ㅠ

**Comment by evan-moon** [comment]
> [첨부파일](https://i.imgur.com/TS2qw7K.png) 아직인듯 합니다 ㅠ

혹시 캐시 한번 지워보시고 다시 시도해보실 수 있을까요? 그리고 Edge 버전 어떤 것 쓰시는 지 알려주시면 디버깅에 더 도움이 될 듯 합니다 :)
저는 Edge 40에서 테스트했었는데 정상 작동되었거든요 ㅜㅜ

**Comment by whatugonnado** [comment]
InPrivate 모드여서 쿠키는 지워진 상태입니다.
Microsoft Edge 44.18362.10022.0
버전이며, 화면 크기가 변함에 따라 깨지는 구간이 생깁니다.

**Comment by evan-moon** [comment]
> InPrivate 모드여서 쿠키는 지워진 상태입니다.
> Microsoft Edge 44.18362.10022.0
> 버전이며, 화면 크기가 변함에 따라 깨지는 구간이 생깁니다.

아이고 ㅜㅜ 다시 한번 확인해보겠습니다!
