### ISSUE TITLE
모바일 환경에서 게시글의 광고가 깨짐

### ISSUE THREAD

**Issue by suites** [evan-moon/evan-blog#7]
![Image from iOS (3)](https://user-images.githubusercontent.com/17154975/66725847-5ae1b500-ee70-11e9-962e-ce3c7fcd4087.png)

모바일로 Evan님의 글을 보다가 발견해서 알려드립니다!
항상 글 잘보고있어요!

**Comment by evan-moon** [comment]
제보 감사합니다 😀
사용하신 브라우저가 safari 같은데 혹시 ios 버전을 알려주실 수 있을까요?ㅎㅎ 정보가 많으면 더 빠른 디버깅을 할 수 있을 것 같습니다!

**Comment by suites** [comment]
> 제보 감사합니다 😀
> 사용하신 브라우저가 safari 같은데 혹시 ios 버전을 알려주실 수 있을까요?ㅎㅎ 정보가 많으면 더 빠른 디버깅을 할 수 있을 것 같습니다!

ios 13.1.2
tmi로 디바이스도 말씀드리면 iPhone 7+ 입니당

**Comment by evan-moon** [comment]
97a1f030136224dbe4a24a53f324b5e7536b3457 에서 수정되었습니다! 감사합니다 🙇🏻‍♂️
