### ISSUE TITLE
TCP handshake 포스팅의 이미지 오타 제보 + 그외

### ISSUE THREAD

**Issue by joshua-qa** [evan-moon/evan-blog#9]
안녕하세요, 항상 글 잘 보고 있어요 :)

다름이 아니라, 이번에 올려주신 포스팅의 이미지에 오타가 있는 것 같아 제보드리려고 해요.

- 본문의 `3way handshake` 설명 파트에서, 이미지 중간의 `SYC+ACK` -> `SYN+ACK`로 수정 필요해보임

한번 확인 부탁드립니다~

그리고 혹시 괜찮으시다면 Discus를 이용한 댓글 기능을 설치해보시는 것도 괜찮을 것 같아요 ㅎㅎ
감사합니다.

**Comment by evan-moon** [comment]
감사합니다 @joshua-qa 님! 바로 수정하겠습니다!

Discus를 사용한 댓글 기능을 고려하고는 있는데 디자인이 너무 난잡해지는 것 같아서 고민 중이에요 ㅜㅜ

**Comment by evan-moon** [comment]
d9ee71367c5f2eb774f3b1e3af6c6c685c4d3349 에서 수정되었습니다! 감사합니다 :)
